export const IMAGE_ROOT = 'http://192.168.0.29/api-curbd/public/images'
export const GOOGLE_MAP_KEY = 'AIzaSyDU1NtxHyVJ8MStzrKJUs2aAFTUu7491BQ'
export const  STRIPE_CLIENT_ID = 'ca_DiEuWG3LP5IskJR5W37loj8WwYbdbSzs'
export const STRIPE_REDIRECT_URI = 'http://localhost:8081/dashboard/trucks'
export const API_URL = 'http://192.168.0.29/api-curbd/public/'
